export const ADD_USER = "ADD_USER";
export const REMOVE_USER = "REMOVE_USER";
export const SET_OWNER_USER = "SET_OWNER_USER";
export const SET_MEDIA_STREAM = "SET_MEDIA_STREAM";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_PARTICIPANT = "UPDATE_PARTICIPANT";
